### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by cloudwaves** [projectsend/projectsend-legacy#2]
Getting below error as there is no such vendor folder present in the projectsend project.

Got error 'PHP message: PHP Warning:  require_once(/var/www/html/projectsend/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/projectsend/bootstrap.php on line 12\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/html/projectsend/vendor/autoload.php' (include_path='.:/usr/share/pear:/usr/share/php') in /var/www/html/projectsend/bootstrap.php on line 12\n'

**Comment by ignacionelson** [comment]
Oh, this is not an error :)
vendor and node_modules folders are not included since they are dependencies and need to be gotten with the corresponding composer and npm commands. Please do not download directly from github as the code here is always in a development state.
A public release does include these dependencies.
